export const ALL_SYSTEM_MOVIES = [
    {
        id: "drishyam-2",
        title: "Drishyam: The Conclusion",
        language: "Hindi",
        genres: ["Drama", "Mystery", "Thriller"],
        format: ["2D"],
        certificate: "UA",
        rating: "8.9",
        votes: "76.4K+ Votes",
        image: "/Drishyam-The-Conclusion-poster-2026.jpeg",
        images: [
            "/Drishyam-The-Conclusion-poster-2026.jpeg",
            "/drishyam2.jpg",
            "/drishyam3.jpg",
        ],
        isUpcoming: false,
    },
    {
        id: "bail",
        title: "Bail",
        language: "Kannada",
        genres: ["Crime", "Drama", "Thriller"],
        format: ["2D"],
        certificate: "UA",
        rating: "8.7",
        votes: "2.8K+ Votes",
        image: "/bail-2026.jpg",
        images: ["/bail-2026.jpg", "/bail.jpg", "/bail2.jpg"],
        isUpcoming: false,
    },
    {
        id: "premada-oorali",
        title: "Premada Oorali",
        language: "Kannada",
        genres: ["Drama", "Romance"],
        format: ["2D"],
        certificate: "U",
        rating: "9.6",
        votes: "46.8K+ Votes",
        image: "/pramad.jpg",
        images: ["/pramad.jpg", "/pramad2.png", "/pramad3.jpeg"],
        isUpcoming: false,
    },
    {
        id: "hanuman-ansh",
        title: "Hanuman Ansh",
        language: "Hindi",
        genres: ["Biography", "Devotional", "Drama"],
        format: ["2D", "3D"],
        certificate: "U",
        rating: "9.6",
        votes: "281K+ Votes",
        image: "/hanumanansh.webp",
        images: ["/hanumanansh.webp", "/hanumanansh2.png", "/hanumanansh3.webp"],
        isUpcoming: false,
    },
    {
        id: "the-social-reckoning",
        title: "The Social Reckoning",
        language: "English",
        genres: ["Biography", "Drama", "Thriller"],
        format: ["2D"],
        certificate: "A",
        rating: "8.4",
        votes: "7.8K+ Likes",
        image: "/the%20social.png",
        images: [
            "/the%20social.png",
            "/thesocial.jpg",
            "/thesocialreckoning_mikeymadison.jpg",
        ],
        isUpcoming: false,
    },
    {
        id: "doremon-castle-undersea",
        title: "Doremon: Castle of the Undersea Devil",
        language: "English",
        genres: ["Animation", "Adventure", "Fantasy"],
        format: ["2D", "3D", "IMAX"],
        certificate: "U",
        rating: "8.8",
        votes: "12.6K+ Votes",
        image: "/doremon1.jpg",
        images: ["/doremon1.jpg", "/doremon2.jpeg", "/doremon3.jpg"],
        isUpcoming: false,
    },
    {
        id: "jailer-2",
        title: "Jailer 2",
        language: "Tamil",
        genres: ["Action", "Thriller"],
        format: ["2D", "IMAX"],
        certificate: "UA",
        rating: "9.2",
        releaseDate: "15, Oct 2026",
        likes: "176K+ Likes",
        image: "/Jailer_2_poster.jpg",
        images: ["/Jailer_2_poster.jpg"],
        isUpcoming: true,
    },
    {
        id: "rajini-jailer-2",
        title: "Rajini: The Jailer 2",
        language: "Tamil",
        genres: ["Action", "Thriller"],
        format: ["2D"],
        certificate: "UA",
        rating: "9.0",
        releaseDate: "15, Oct 2026",
        likes: "133K+ Likes",
        image: "/Jailer2.jpeg",
        images: ["/Jailer2.jpeg"],
        isUpcoming: true,
    },
    {
        id: "emperor-sarat-chandra",
        title: "Emperor vs Sarat Chandra",
        language: "Hindi",
        genres: ["Drama", "Historical", "Political"],
        format: ["2D"],
        certificate: "UA",
        rating: "8.5",
        releaseDate: "16, Oct 2026",
        likes: "20.7K+ Likes",
        image: "/Emperor_vs_Sarat_Chandra_poster.jpg",
        images: ["/Emperor_vs_Sarat_Chandra_poster.jpg"],
        isUpcoming: true,
    },
    {
        id: "bohurupi-golden-daku",
        title: "Bohurupi: The Golden Daku",
        language: "Hindi",
        genres: ["Action", "Drama", "Thriller"],
        format: ["2D"],
        certificate: "UA",
        rating: "8.6",
        releaseDate: "17, Oct 2026",
        likes: "14.7K+ Likes",
        image: "/baharupi2.jpg",
        images: ["/baharupi2.jpg"],
        isUpcoming: true,
    },
];

export const NOW_SHOWING_MOVIES = ALL_SYSTEM_MOVIES.filter((m) => !m.isUpcoming);
export const UPCOMING_MOVIES = ALL_SYSTEM_MOVIES.filter((m) => m.isUpcoming);
